### ISSUE TITLE
Fatal error in customers export

### ISSUE THREAD

**Issue by wallaceer** [vanquyet94/disabled-customers-magento2#1]
Hi,
when I try to export the customers I receive this error
<<
Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\View\Element\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 220 and defined in /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php:172 Stack trace: #0 /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php(220): Magento\Framework\View\Element\UiComponentFactory->argumentsResolver('account_is_bloc...', NULL) #1 /var/www/html/vendor/magento/module-ui/Component/Listing/Columns/Column.php(77): Magento\Framework\View\Element\UiComponentFactory->create('account_is_bloc...', 'int', Array) #2 /var/www/html/vendor/magento/module-ui/Component/MassAction/Filter.php(182): Magento\Ui\Component\Listing\Columns\Column->prepare() #3 /var/www/html/vendor/magento/module-ui/Component/MassAction/Filter.php(180): Magento\Ui\Component\MassAction\Filter->prepareComponent(Object(VoolaTech\CustomerBlock\Ui\Comp in /var/www/html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172
>> 

I think it is generated by prepareComponent(Object(VoolaTech\CustomerBlock\Ui\Component\Listing\Column\Activation.php

Can you help me?
I work with Magento CE 2.2.7

Thanks,
Walter

**Comment by sunboy88** [comment]
Please try this solution: UPDATE eav_attribute SET frontend_input = 'text' WHERE attribute_code = 'your_attribute_code';
